TARGET_OS := gnu_linux
TARGET_CPU_SMP := true
TARGET_ARCH := x86
TARGET_ARCH_VARIANT := x86
TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := true
TARGET_CPU_ABI := x86
TARGET_CPU_VARIANT := x86
TARGET_PRELINK_MODULE := false
TARGET_BUILD_TYPE=debug

DALVIK_VM_LIB := libart.so
